# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspaces/bf/tilck

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspaces/bf/tilck/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/bf/tilck/build/CMakeFiles /workspaces/bf/tilck/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/bf/tilck/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /workspaces/bf/tilck/build/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named generated_configuration

# Build rule for target.
generated_configuration: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 generated_configuration
.PHONY : generated_configuration

# fast build rule for target.
generated_configuration/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generated_configuration.dir/build.make CMakeFiles/generated_configuration.dir/build
.PHONY : generated_configuration/fast

#=============================================================================
# Target rules for targets named userapps

# Build rule for target.
userapps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 userapps
.PHONY : userapps

# fast build rule for target.
userapps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/userapps.dir/build.make CMakeFiles/userapps.dir/build
.PHONY : userapps/fast

#=============================================================================
# Target rules for targets named kernel

# Build rule for target.
kernel: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kernel
.PHONY : kernel

# fast build rule for target.
kernel/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/build
.PHONY : kernel/fast

#=============================================================================
# Target rules for targets named boot_legacy

# Build rule for target.
boot_legacy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 boot_legacy
.PHONY : boot_legacy

# fast build rule for target.
boot_legacy/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boot_legacy.dir/build.make CMakeFiles/boot_legacy.dir/build
.PHONY : boot_legacy/fast

#=============================================================================
# Target rules for targets named efi_x86_64

# Build rule for target.
efi_x86_64: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 efi_x86_64
.PHONY : efi_x86_64

# fast build rule for target.
efi_x86_64/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/efi_x86_64.dir/build.make CMakeFiles/efi_x86_64.dir/build
.PHONY : efi_x86_64/fast

#=============================================================================
# Target rules for targets named efi_ia32

# Build rule for target.
efi_ia32: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 efi_ia32
.PHONY : efi_ia32

# fast build rule for target.
efi_ia32/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/efi_ia32.dir/build.make CMakeFiles/efi_ia32.dir/build
.PHONY : efi_ia32/fast

#=============================================================================
# Target rules for targets named efi_bootloader

# Build rule for target.
efi_bootloader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 efi_bootloader
.PHONY : efi_bootloader

# fast build rule for target.
efi_bootloader/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/efi_bootloader.dir/build.make CMakeFiles/efi_bootloader.dir/build
.PHONY : efi_bootloader/fast

#=============================================================================
# Target rules for targets named tilck_image

# Build rule for target.
tilck_image: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tilck_image
.PHONY : tilck_image

# fast build rule for target.
tilck_image/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tilck_image.dir/build.make CMakeFiles/tilck_image.dir/build
.PHONY : tilck_image/fast

#=============================================================================
# Target rules for targets named test_fatpart_target

# Build rule for target.
test_fatpart_target: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_fatpart_target
.PHONY : test_fatpart_target

# fast build rule for target.
test_fatpart_target/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fatpart_target.dir/build.make CMakeFiles/test_fatpart_target.dir/build
.PHONY : test_fatpart_target/fast

#=============================================================================
# Target rules for targets named gtests

# Build rule for target.
gtests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtests
.PHONY : gtests

# fast build rule for target.
gtests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gtests.dir/build.make CMakeFiles/gtests.dir/build
.PHONY : gtests/fast

#=============================================================================
# Target rules for targets named merge_compile_commands

# Build rule for target.
merge_compile_commands: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 merge_compile_commands
.PHONY : merge_compile_commands

# fast build rule for target.
merge_compile_commands/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/merge_compile_commands.dir/build.make CMakeFiles/merge_compile_commands.dir/build
.PHONY : merge_compile_commands/fast

#=============================================================================
# Target rules for targets named fathack

# Build rule for target.
fathack: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fathack
.PHONY : fathack

# fast build rule for target.
fathack/fast:
	$(MAKE) $(MAKESILENT) -f scripts/build_apps/CMakeFiles/fathack.dir/build.make scripts/build_apps/CMakeFiles/fathack.dir/build
.PHONY : fathack/fast

#=============================================================================
# Target rules for targets named pnm2text

# Build rule for target.
pnm2text: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pnm2text
.PHONY : pnm2text

# fast build rule for target.
pnm2text/fast:
	$(MAKE) $(MAKESILENT) -f scripts/build_apps/CMakeFiles/pnm2text.dir/build.make scripts/build_apps/CMakeFiles/pnm2text.dir/build
.PHONY : pnm2text/fast

#=============================================================================
# Target rules for targets named mbrhack

# Build rule for target.
mbrhack: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mbrhack
.PHONY : mbrhack

# fast build rule for target.
mbrhack/fast:
	$(MAKE) $(MAKESILENT) -f scripts/build_apps/CMakeFiles/mbrhack.dir/build.make scripts/build_apps/CMakeFiles/mbrhack.dir/build
.PHONY : mbrhack/fast

#=============================================================================
# Target rules for targets named gen_config

# Build rule for target.
gen_config: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gen_config
.PHONY : gen_config

# fast build rule for target.
gen_config/fast:
	$(MAKE) $(MAKESILENT) -f scripts/build_apps/CMakeFiles/gen_config.dir/build.make scripts/build_apps/CMakeFiles/gen_config.dir/build
.PHONY : gen_config/fast

#=============================================================================
# Target rules for targets named elfhack32

# Build rule for target.
elfhack32: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 elfhack32
.PHONY : elfhack32

# fast build rule for target.
elfhack32/fast:
	$(MAKE) $(MAKESILENT) -f scripts/build_apps/CMakeFiles/elfhack32.dir/build.make scripts/build_apps/CMakeFiles/elfhack32.dir/build
.PHONY : elfhack32/fast

#=============================================================================
# Target rules for targets named elfhack64

# Build rule for target.
elfhack64: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 elfhack64
.PHONY : elfhack64

# fast build rule for target.
elfhack64/fast:
	$(MAKE) $(MAKESILENT) -f scripts/build_apps/CMakeFiles/elfhack64.dir/build.make scripts/build_apps/CMakeFiles/elfhack64.dir/build
.PHONY : elfhack64/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... boot_legacy"
	@echo "... efi_bootloader"
	@echo "... efi_ia32"
	@echo "... efi_x86_64"
	@echo "... generated_configuration"
	@echo "... gtests"
	@echo "... kernel"
	@echo "... merge_compile_commands"
	@echo "... test_fatpart_target"
	@echo "... tilck_image"
	@echo "... userapps"
	@echo "... elfhack32"
	@echo "... elfhack64"
	@echo "... fathack"
	@echo "... gen_config"
	@echo "... mbrhack"
	@echo "... pnm2text"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /workspaces/bf/tilck/build/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

