/* SPDX-License-Identifier: BSD-2-Clause */

/*
 * This is a TEMPLATE. The actual config file is generated by CMake and stored
 * in <BUILD_DIR>/tilck_gen_headers/.
 */

#pragma once
#define ALL_MODULES_LIST         "acpi console debugpanel e1000 fb goldfish kb8042 null pci ramfb riscv_irq sb16 serial sysfs systests tracing"
