/* This file is AUTO-GENERATED by the gen_config tool */

#include "/workspaces/bf/tilck/modules/sysfs/ro_config_vars.h"

#include <tilck_gen_headers/mod_kb8042.h>
#include <tilck_gen_headers/mod_fb.h>
#include <tilck_gen_headers/mod_sysfs.h>
#include <tilck_gen_headers/mod_null.h>
#include <tilck_gen_headers/mod_acpi.h>
#include <tilck_gen_headers/mod_riscv_irq.h>
#include <tilck_gen_headers/mod_goldfish.h>
#include <tilck_gen_headers/mod_sb16.h>
#include <tilck_gen_headers/mod_debugpanel.h>
#include <tilck_gen_headers/mod_serial.h>
#include <tilck_gen_headers/mod_pci.h>
#include <tilck_gen_headers/mod_ramfb.h>
#include <tilck_gen_headers/mod_systests.h>
#include <tilck_gen_headers/mod_tracing.h>
#include <tilck_gen_headers/mod_e1000.h>
#include <tilck_gen_headers/mod_console.h>

static void sysfs_fail_to_register_obj(const char *name);

/* modules */
DEF_STATIC_CONF_RO(BOOL, kb8042, MOD_kb8042);
DEF_STATIC_CONF_RO(BOOL, fb, MOD_fb);
DEF_STATIC_CONF_RO(BOOL, sysfs, MOD_sysfs);
DEF_STATIC_CONF_RO(BOOL, null, MOD_null);
DEF_STATIC_CONF_RO(BOOL, acpi, MOD_acpi);
DEF_STATIC_CONF_RO(BOOL, riscv_irq, MOD_riscv_irq);
DEF_STATIC_CONF_RO(BOOL, goldfish, MOD_goldfish);
DEF_STATIC_CONF_RO(BOOL, sb16, MOD_sb16);
DEF_STATIC_CONF_RO(BOOL, debugpanel, MOD_debugpanel);
DEF_STATIC_CONF_RO(BOOL, serial, MOD_serial);
DEF_STATIC_CONF_RO(BOOL, pci, MOD_pci);
DEF_STATIC_CONF_RO(BOOL, ramfb, MOD_ramfb);
DEF_STATIC_CONF_RO(BOOL, systests, MOD_systests);
DEF_STATIC_CONF_RO(BOOL, tracing, MOD_tracing);
DEF_STATIC_CONF_RO(BOOL, e1000, MOD_e1000);
DEF_STATIC_CONF_RO(BOOL, console, MOD_console);

DEF_STATIC_SYSOBJ_TYPE(
   type_config,
   &prop_buildtype,
   &prop_version,
   &prop_arch,
   &prop_commit,
   &prop_debugchecks,
   NULL
);

DEF_STATIC_SYSOBJ(
   obj_config,
   &type_config,
   NULL /* hooks */,
   &conf_buildtype,
   &conf_version,
   &conf_arch,
   &conf_commit,
   &conf_debugchecks,
);

DEF_STATIC_SYSOBJ_TYPE(
   type_console,
   &prop_big_font_threshold,
   &prop_banner,
   &prop_cursor_blink,
   &prop_use_alt_fonts,
   &prop_show_logo,
   &prop_big_scroll_buf,
   &prop_failsafe_opt,
   NULL
);

DEF_STATIC_SYSOBJ(
   obj_console,
   &type_console,
   NULL /* hooks */,
   &conf_big_font_threshold,
   &conf_banner,
   &conf_cursor_blink,
   &conf_use_alt_fonts,
   &conf_show_logo,
   &conf_big_scroll_buf,
   &conf_failsafe_opt,
);

DEF_STATIC_SYSOBJ_TYPE(
   type_kernel,
   &prop_timer_hz,
   &prop_sched_latency_ticks,
   &prop_min_granularity_ticks,
   &prop_stack_pages,
   &prop_user_stack_pages,
   &prop_track_nested_int,
   &prop_panic_backtrace,
   &prop_panic_regs,
   &prop_selftests,
   &prop_stack_isolation,
   &prop_symbols,
   &prop_printk_on_curr_tty,
   &prop_resched_enable_preempt,
   &prop_big_io_buf,
   &prop_gcov,
   &prop_fork_no_cow,
   &prop_mmap_no_cow,
   &prop_ubsan,
   &prop_kernel_64bit_offt,
   NULL
);

DEF_STATIC_SYSOBJ(
   obj_kernel,
   &type_kernel,
   NULL /* hooks */,
   &conf_timer_hz,
   &conf_sched_latency_ticks,
   &conf_min_granularity_ticks,
   &conf_stack_pages,
   &conf_user_stack_pages,
   &conf_track_nested_int,
   &conf_panic_backtrace,
   &conf_panic_regs,
   &conf_selftests,
   &conf_stack_isolation,
   &conf_symbols,
   &conf_printk_on_curr_tty,
   &conf_resched_enable_preempt,
   &conf_big_io_buf,
   &conf_gcov,
   &conf_fork_no_cow,
   &conf_mmap_no_cow,
   &conf_ubsan,
   &conf_kernel_64bit_offt,
);

DEF_STATIC_SYSOBJ_TYPE(
   type_modules,
   &prop_kb8042,
   &prop_fb,
   &prop_sysfs,
   &prop_null,
   &prop_acpi,
   &prop_riscv_irq,
   &prop_goldfish,
   &prop_sb16,
   &prop_debugpanel,
   &prop_serial,
   &prop_pci,
   &prop_ramfb,
   &prop_systests,
   &prop_tracing,
   &prop_e1000,
   &prop_console,
   NULL
);

DEF_STATIC_SYSOBJ(
   obj_modules,
   &type_modules,
   NULL /* hooks */,
   &conf_kb8042,
   &conf_fb,
   &conf_sysfs,
   &conf_null,
   &conf_acpi,
   &conf_riscv_irq,
   &conf_goldfish,
   &conf_sb16,
   &conf_debugpanel,
   &conf_serial,
   &conf_pci,
   &conf_ramfb,
   &conf_systests,
   &conf_tracing,
   &conf_e1000,
   &conf_console,
);


void
sysfs_create_config_obj(void)
{
   struct sysobj *root = &sysfs_root_obj;
   const char *name;

   name = "config";
   if (sysfs_register_obj(NULL, root, name, &obj_config))
      goto fail;

   name = "console";
   if (sysfs_register_obj(NULL, root, name, &obj_console))
      goto fail;

   name = "kernel";
   if (sysfs_register_obj(NULL, root, name, &obj_kernel))
      goto fail;

   name = "modules";
   if (sysfs_register_obj(NULL, root, name, &obj_modules))
      goto fail;


   return; /* success */

fail:
   sysfs_fail_to_register_obj(name);
}
