/* SPDX-License-Identifier: BSD-2-Clause */

/*
 * This is a TEMPLATE. The actual config header file is generated by CMake
 * and put in <BUILD_DIR>/kernel/tilck_gen_headers/.
 *
 * Kernel-private console module config. Shared module variables (MOD_console,
 * TTY_COUNT, SERIAL_CON_IN_VIDEO_MODE, etc.) are in modules_config.h.
 */

#pragma once
#include <tilck_gen_headers/modules_config.h>

/* ------ Value-based config variables -------- */

#define KRN_TERM_SCROLL_LINES      5

/* --------- Kernel-private boolean config variables --------- */

#define    KRN_SHOW_LOGO 1
#define    KRN_PRINTK_ON_CURR_TTY 1

#ifdef KERNEL_TEST
   #define MOD_console_actual 1
#else
   #define MOD_console_actual MOD_console
#endif

/*
 * --------------------------------------------------------------------------
 *                  Hard-coded global & derived constants
 * --------------------------------------------------------------------------
 */

#define TTY_INPUT_BS                                              1024
#define FAILSAFE_COLS                                              80u
#define FAILSAFE_ROWS                                              25u
