/* SPDX-License-Identifier: BSD-2-Clause */

/*
 * This is a TEMPLATE. The actual config file is generated by CMake and stored
 * in <BUILD_DIR>/tilck_gen_headers/.
 */

#pragma once
#include <tilck_gen_headers/config_global.h>
#include <tilck/common/page_size.h>

#define KERNEL_FILE_PATH       "/tilck"

#define SECTOR_SIZE            512
#define BL_ST2_DATA_SEG        0x2000
#define BL_BASE_ADDR           0x22000
#define BL_BASE_SEG            (0x22000 / 16)
#define DISK_UUID              0x4906062b
#define IMG_SZ_SEC             73728       /* size of the whole image */
#define BOOT_SECTORS           128     /* bootloader sectors      */
#define BOOTPART_SEC           128     /* start of the bootpart   */
#define BOOTPART_SZ_SEC        6144  /* size of the bootpart    */
#define INITRD_SECTOR          6272    /* start of the initrd     */
#define INITRD_SZ_SEC          65536    /* size of the initrd      */
#define PREFERRED_GFX_MODE_W   800
#define PREFERRED_GFX_MODE_H   600

/* Boolean config variables */
#define BOOTLOADER_POISON_MEMORY 0
#define BOOT_INTERACTIVE 1
#define EFI_BOOTLOADER_DEBUG 0
