/* SPDX-License-Identifier: BSD-2-Clause */
/* style_check: disable hex_literal_lowercase */

/*
 * This is a TEMPLATE. The actual config file is generated by CMake and stored
 * in <BUILD_DIR>/tilck_gen_headers/.
 */


#pragma once

#define KB (1024u)
#define MB (1024u * 1024u)

#define VER_MAJOR              0
#define VER_MINOR              1
#define VER_PATCH              4

#define VER_MAJOR_STR          "0"
#define VER_MINOR_STR          "1"
#define VER_PATCH_STR          "4"

#define ARCH_GCC_TC            "i686"
#define PROJ_BUILD_DIR         "/workspaces/bf/tilck/build"
#define BUILDTYPE_STR          "Debug"

#define DEVSHELL_PATH          "/initrd/usr/bin/devshell"

#define KERNEL_STACK_PAGES     4
#define KERNEL_PADDR           0x00100000
#define BASE_VA                0xC0000000
#define LINEAR_MAPPING_MB      896UL
#define KERNEL_BASE_VA         0xC0000000
#define KERNEL_VADDR           0xC0100000

#define ARCH_BITS              32

/* --------- Boolean config variables --------- */

#define FAT_TEST_DIR 0
#define DEBUG_CHECKS 1

/* ----------- Convenience defines ------------ */

#if DEBUG_CHECKS
   #ifdef NDEBUG
      #undef NDEBUG
   #endif
#endif

#ifdef KERNEL_TEST
   #define KERNEL_TEST_INT 1
#else
   #define KERNEL_TEST_INT 0
#endif

#ifdef TILCK_RELEASE_BUILD
   #define IS_RELEASE_BUILD 1
#else
   #define IS_RELEASE_BUILD 0
#endif

/* ----------- Derived constants ----------- */

#if defined(TESTING) || defined(KERNEL_TEST)

   extern void *base_va;

   /* For the unit tests, we need to override the following defines */
   #undef BASE_VA
   #undef LINEAR_MAPPING_MB

   #define BASE_VA                    ((ulong)base_va)
   #define LINEAR_MAPPING_MB          (128u)

#endif

#define LINEAR_MAPPING_SIZE        (LINEAR_MAPPING_MB << 20)
#define LINEAR_MAPPING_END         (BASE_VA + LINEAR_MAPPING_SIZE)

/* Constants that have no reason to be changed */
#define FREE_MEM_POISON_VAL    0xFAABCAFE

/*
 * ----------- User tasks constants -----------
 *
 * WARNING: some of them are NOT really "configurable" without having to modify
 * a lot of code. Think about the potential implications changing the following
 * constants or, worse, before promoting them to be configurable as CMake
 * variables.
 */
#define USER_ARGS_PAGE_COUNT                                    1
#define MAX_TTYS                                                9
#define MAX_PATH                                              256
#define MAX_PID                                              8191
