/* SPDX-License-Identifier: BSD-2-Clause */

/*
 * This is a TEMPLATE. The actual config file is generated by CMake and stored
 * in <BUILD_DIR>/tilck_gen_headers/.
 *
 * Shared kernel config: only variables needed by boot/userapps code.
 * Kernel-private kernel variables are in config/kernel/config_kernel.h.
 */

#pragma once
#include <tilck_gen_headers/config_global.h>

#define HAVE_KERNEL_CONFIG

/* --------- Boolean config variables --------- */
#define KERNEL_FORCE_TC_ISYSTEM 0
#define KERNEL_SAT 0
#define KERNEL_64BIT_OFFT 1
