/* SPDX-License-Identifier: BSD-2-Clause */

/*
 * This is a TEMPLATE. The actual config file is generated by CMake and stored
 * in <BUILD_DIR>/tilck_gen_headers/.
 *
 * Shared debug config: only variables needed by boot/userapps code.
 * Kernel-private debug variables are in config/kernel/config_debug.h.
 */

#pragma once
#include <tilck_gen_headers/config_kernel.h>

/* --------- Boolean config variables --------- */

#define PANIC_SHOW_STACKTRACE 1
#define PANIC_SHOW_REGS 0
