/* SPDX-License-Identifier: BSD-2-Clause */

/*
 * This is a TEMPLATE. The actual config header file is generated by CMake
 * and put in <BUILD_DIR>/tilck_gen_headers/.
 */

#pragma once

#define    MOD_e1000 0

