/* Auto-generated by root CMake. Do not edit. */

#pragma once

/* Module enable/disable flags */
#define MOD_acpi 1
#define MOD_console 1
#define MOD_debugpanel 1
#define MOD_e1000 0
#define MOD_fb 1
#define MOD_goldfish 1
#define MOD_kb8042 1
#define MOD_null 1
#define MOD_pci 1
#define MOD_ramfb 1
#define MOD_riscv_irq 1
#define MOD_sb16 1
#define MOD_serial 1
#define MOD_sysfs 1
#define MOD_systests 1
#define MOD_tracing 1

/* Shared module config variables */
#define TTY_COUNT              2
#define SERIAL_CON_IN_VIDEO_MODE 1
#define KERNEL_SERCON 0
#define TERM_BIG_SCROLL_BUF 0
#define PS2_DO_SELFTEST 0
#define PS2_VERBOSE_DEBUG_LOG 0
